name = "The-InBetween"
author = "Conquerix"
version = "v0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9c1e8b863740ca97a2ae8b87937a09d59add5b39b483d8f717fc86f2121badf7"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
