name = "The-InBetween"
author = "Conquerix"
version = "v0.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7e2bfc1d06aa669cb5527417a015bacd72557b9e96504ea2ba64d36b8ff6ffd2"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
