name = "The-InBetween"
author = "Conquerix"
version = "v0.5.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f4068e85b4607e154bccaa073532993f690d5705b9c7abed26fbb1286e03060"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
