name = "The-InBetween"
author = "Conquerix"
version = "v0.5.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f44cc7b69b3b1abc1f8072f357fb7dce3649c9c4a2feb9e989c15c3de0172754"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
