name = "The-InBetween"
author = "Conquerix"
version = "v0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f970cb5c3623590d0335d81b968aa3da92fce09166daf91af000c58258262ba6"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
