name = "The-InBetween"
author = "Conquerix"
version = "v0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3fc6dd774152b1d9ce88adb1663270b7e1804dd47be6ee5e83feb65c57cd0318"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
