name = "The-InBetween"
author = "Conquerix"
version = "v0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f592f3964629a24e469ebddd3a403bc8463b386b3c88ed3eedc7a915d07a6e73"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
