name = "The-InBetween"
author = "Conquerix"
version = "v0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "673bfd7614270cb4b2181a848b473f69c81eeadff3a23b480b6891bc95e9932d"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
