name = "The-InBetween"
author = "Conquerix"
version = "v0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ba20503eceded00e2120a498e842ef2722db83ebdf8b185bc61a0299b88cb05"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
