name = "The-InBetween"
author = "Conquerix"
version = "v0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "438476bfe98af9facdc19687a720a32bc466f7d3eef63365bba08b2f70fda09d"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
