name = "The-InBetween"
author = "Conquerix"
version = "v0.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "511348498c273b3eee7c1a78f131aac8143eab41e174d98b8511af14caf1646e"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
