name = "The InBetween"
author = "Conquerix"
version = "client-v0.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "197a99dc3c093a33630d120deeb4db0ca0b5f3cef826d001830fc795bef154ac"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
