name = "The-InBetween"
author = "Conquerix"
version = "v0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "819017aed922b3fa1f9af90c0d9dbfa3392bc580c39ac75856a208fabdd54d2d"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
