name = "The-InBetween"
author = "Conquerix"
version = "v0.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eda8b1cfb768a6ca3f052f4ef012351142073381f41a8dd56a6d875837b6f49f"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
