name = "The InBetween"
author = "Conquerix"
version = "v0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fe436e03d12a1b1c27ebbb59ee584f6625a42bb0181ec43862b608943213556"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
