name = "The-InBetween"
author = "Conquerix"
version = "v0.5.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a43d6d5f0214f652b7b15ebce56e09339ac541c4d1ff2315665fbae5c0d9f71"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
