name = "The-InBetween"
author = "Conquerix"
version = "v0.8.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1a8db158693430fd0b8eb8b161044c2f2c3216d7586fa6ca9a3767d332e64b4"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
