name = "The-InBetween"
author = "Conquerix"
version = "v0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c5624c19cee4aed44e407bf0c1d841be63741dff93ead9a07c995b91081c8c72"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
