name = "The-InBetween"
author = "Conquerix"
version = "v0.5.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf9c2a1373b5cff43cb7d0bdb30915da8dfeb75a3d7da02a3c123c02069bc3da"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
