name = "The-InBetween"
author = "Conquerix"
version = "v0.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de99d553ebb752cb45693c62ff163fa3a27d1c8a1c90dd6ad6d229649ccb4412"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
