name = "The InBetween"
author = "Conquerix"
version = "v0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7df01ef5f9684aa8a233d4b04a445279904755b1b0f46d51fd04aed7d4541c1"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
