name = "The-InBetween"
author = "Conquerix"
version = "v0.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99e65a9bc32cf357d0e0cfea1a4b16d805cf86e1f244767b22cf286bead45b6a"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
