name = "The InBetween"
author = "Conquerix"
version = "client-v0.1.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "68712dba7af0ca23e60ca5fcf2a7f86dcfb55f9a79304da308ee4d6215cf8579"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
