name = "The-InBetween"
author = "Conquerix"
version = "v0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "28139756d185d3e66ec52adcbb1f4bf377d1c80ff9d7100ae291e0eea609223e"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
