name = "The-InBetween"
author = "Conquerix"
version = "v0.7.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a9465ca047d07f00c4353776b32031bc6b92b0657d3436ad37b5e1fcc3f4291"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
