name = "The-InBetween"
author = "Conquerix"
version = "v0.4.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "30930d6876b643a4e81b28cd472f27cc2826096ab207314a9cdd69670e26226f"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
