name = "The-InBetween"
author = "Conquerix"
version = "v0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8013256cf8484d6ef944bb4f15173a540909e88dfc5f7ba1e6f29854358e0d78"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
