name = "The-InBetween"
author = "Conquerix"
version = "v0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edd99d2104098ba81d0758d0331be4bd47fd63953be5acd8c560bedf28fb3c62"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
