name = "The-InBetween"
author = "Conquerix"
version = "v0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6ad966cb888e1f11aa1d4746dc5c77d3dcc459de31d2d92c3ad477f21d3b827b"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
