name = "The-InBetween"
author = "Conquerix"
version = "v0.5.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3d3bee2dda8e9e34bb48a2e8be9daaf38e92fce4a0f63697ae7875aa0d2e89eb"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
