name = "The InBetween"
author = "Conquerix"
version = "client-v0.1.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5c4c281aabb3418ccb46c47a8f4e1c72a37c271fcc3fa5efdeaeac31667d81c3"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
