name = "The-InBetween"
author = "Conquerix"
version = "v0.4.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "efaf5e84df2282492a6d2ac828a78b16c03d3552fda1b872963fb3b01ff3789b"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
