name = "The-InBetween"
author = "Conquerix"
version = "v0.4.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db124e32b28e235f432cb270325b65b953a0d014005d095032f1eff7baa352a7"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
