name = "The-InBetween"
author = "Conquerix"
version = "v0.8.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "60ffc2ad0c9fe745f5526cee77637d182c8d06be1beef886419c35e8c199add2"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
