name = "The InBetween"
author = "Conquerix"
version = "client-v0.1.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "993629a3ea4d3896000cec349c091b744e0e031e4271eafccd74c0e54907b43c"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
