name = "The-InBetween"
author = "Conquerix"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3efc1c4152e6621f1b8eb60996278bc1e22c05bf8bb12a6ddf010c7c8fb19826"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
