name = "The InBetween"
author = "Conquerix"
version = "client-v0.1.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e96de5e728bf566c78019bdc6a26e06c7fbdbb06589e895f49498edd84feaa99"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
