name = "The-InBetween"
author = "Conquerix"
version = "v0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca98f4b2541ce648e2015f6ff52674e701b3bd8b9419abe324dfbd7200c0dd38"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
