name = "The-InBetween"
author = "Conquerix"
version = "v0.5.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23ccb00b3981350f9e6e1d32a7dfae60dbbcc228d1141cae14ae8016c5d51afa"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
