name = "The-InBetween"
author = "Conquerix"
version = "v0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57e312ad90470f3ad8ae83fe263dc824b933e50f2090c77b618630228e0406e6"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
