name = "The-InBetween"
author = "Conquerix"
version = "v0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7941c11a796e23ffc6326a819da9e7a92b984a58a691540b4d09cea1894ba35"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
