name = "The-InBetween"
author = "Conquerix"
version = "v0.8.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e958be68665943aefbd2cffc969b8e84407ec6a0b28c7b78b25b8ce8468b983"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
