name = "The-InBetween"
author = "Conquerix"
version = "v0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "764cbafab1956d2116b37823227b3141251be1c5d9f09d606ce40030ba9febdb"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
