name = "The-InBetween"
author = "Conquerix"
version = "v0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab0d40657fef0c1968b49f41adb1287ba33cbb19b9e33b59c741a0910c0df5dc"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
