name = "The-InBetween"
author = "Conquerix"
version = "v0.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "007d90ce8d8cd9dee98f97a6295c2c10581c5b7ff898c7c229cffccafbfdfcdc"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
