name = "The-InBetween"
author = "Conquerix"
version = "v0.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20855159fc5b43f98814642ed08e1e7188b1c58933e9af3c11477beb18b1179d"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
