name = "The-InBetween"
author = "Conquerix"
version = "v0.5.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4bd97ae1a90f984048405f75f2aff8a0dacb011bded02fdc48b51d3197b0e2c4"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
