name = "The-InBetween"
author = "Conquerix"
version = "v0.8.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82d4ffb0898e9104040caeeb1a18d2f9043f60be96074da05c650ff3454a40dd"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
