name = "The-InBetween"
author = "Conquerix"
version = "v0.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "292da86af6272c5178d7a327b1837a88718e11433adb31f836ff6be48e193847"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
