name = "The-InBetween"
author = "Conquerix"
version = "v0.8.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad213b9acadbb6c638b453b26f8711fe1c9cdcd201058a4bc61d77700cb39405"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
