name = "The-InBetween"
author = "Conquerix"
version = "v0.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9969576ea12db9015a4c10b840177ee46200f604fd6930b827fc5a8062a8a832"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
