name = "The-InBetween"
author = "Conquerix"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "618700323d19ce264165c28cf3e5f767e34fd53042159d6e65ae47a149bb35d2"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
