name = "The-InBetween"
author = "Conquerix"
version = "v0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f91cb4feb2eaf645aba3fa870d510046f5d00745474fde22c9577049d4cf5cb"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
