{
  "release-type": "simple",
  "bump-minor-pre-major": true,
  "bump-patch-for-minor-pre-major": true,
  "changelog-sections": [
    {"type":"feat","section":"★ Features","hidden":false},
    {"type":"fix","section":"♻ Bug Fixes","hidden":false},
    {"type":"mod","section":"☀ Modpack Changes","hidden":false},
    {"type":"update","section":"⚘ Modpack Updates","hidden":false},
    {"type":"chore","section":"⛭ Miscellaneous","hidden":true}
  ],
  "draft": true,
  "prerelease": true
}
