name: 'Release Modpack From A Release | Action'
description: 'This automatically downloads the newest release and description and uploads it to vendors!'
inputs:
  loader:
    description: "Current Modpack Loader"
    required: true
  game-version:
    description: "Current Modpack Game Version"
    required: true

  MODRINTH-TOKEN:
    required: true
    description: "Token used to uploading modpack to Modrinth"
  MODRINTH-ID:
    required: true
    description: "ID used to uploading modpack to Modrinth"


runs:
    using: "composite"
    steps:
      - name: Check Out Git Repository
        uses: actions/checkout@v3

      - name: Get Latest tag
        id: tag
        uses: WyriHaximus/github-action-get-previous-tag@v1

      - name: Download the pack files
        uses: robinraju/release-downloader@v1.8
        id: download-files
        with:
          fileName: "*"
          tag: ${{ steps.tag.outputs.tag }}
          tarBall: false
          zipBall: false

      
      - name: Get latest release description
        uses: cardinalby/git-get-release-action@v1
        id: latest-release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag: ${{ steps.tag.outputs.tag }}

      - name: Set publish version-type
        id: release-type
        run: |
          if [ "${{ steps.latest-release.outputs.prerelease }}" = "true" ]; then
            echo "Setting release-type to beta"
            echo "release-type=beta" >> $GITHUB_OUTPUT
          else
            echo "Setting release-type to release"
            echo "release-type=release" >> $GITHUB_OUTPUT
          fi
        shell: bash

      - name: Pipe latest release description to file
        run: echo "${{ steps.latest-release.outputs.body }}" > CHANGELOG.release.md
        shell: bash

      - name: Print status
        run: |
          echo "::notice ::⚙ Assets from latest release ${{ steps.latest-release.outputs.tag_name }} downloaded successfully!"
          echo "::notice ::⚙ Latest release ${{ steps.latest-release.outputs.tag_name }} description piped into a file successfully!"
        shell: bash

      - name: Publish to Modrinth
        id: modrinth
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          modrinth-id: ${{ inputs.MODRINTH-ID }}
          modrinth-token: ${{ inputs.MODRINTH-TOKEN }}
          loaders: ${{ inputs.loader }}
          game-versions: ${{ inputs.game-version }}
          changelog-file: CHANGELOG.release.*
          files: "*.zip"
          version: ${{ steps.tag.outputs.tag }}
          version-type: ${{ steps.release-type.outputs.release-type }}

      - name: Print Modrinth upload status
        if: steps.modrinth.outcome == 'success'
        run: |
          echo "::notice ::☀ Modpack successfully uploaded to Modrinth!"
        shell: bash
