name = "The InBetween"
author = "Conquerix"
version = "v0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f90c070a3ac6150115e7d144d8ebaea461a5f0501ad853e049ba7a1e39a0e91"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
