name = "The-InBetween"
author = "Conquerix"
version = "v0.5.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ddb6a243e5ca76540d5db5a2cacb8deb95c9e26611bf9753f657b68f29332498"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
