name = "The-InBetween"
author = "Conquerix"
version = "v0.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f95166148c4e025322b48f4b0f71f3f39c90562625cc62bfde346c7c443e04f8"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
