name = "The-InBetween"
author = "Conquerix"
version = "v0.4.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a5835af7046bf8ba9789b0ea8ef2b0a17795a571d1cbac6f20b0ce3c55ab40c"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
