name = "The-InBetween"
author = "Conquerix"
version = "v0.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ebe6265fc181cc576d428d64106dee071bc208d89b3bbaaccfd4c559ac3a3f0"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
