name = "The InBetween"
author = "Conquerix"
version = "v0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86a954e4fdc235226983c9b6c55e8db3f2c836cce616b0d371e9dcaf122d347c"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
