name = "The-InBetween"
author = "Conquerix"
version = "v0.4.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2af65506db621f0eb2ba7931c1b58110516b78854cf980b18b1ed61125225591"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
