name = "The-InBetween"
author = "Conquerix"
version = "v0.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "adf51fccfccaaeb186923f30be7ee5f6bc3e59ce81035a472f594d6c8dbcf9be"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
