name = "The-InBetween"
author = "Conquerix"
version = "v0.5.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a577d3678f3d8f1149416a91e68214582d9a5b680e3e1e6e0ce4ad533015ba5"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
