name = "The-InBetween"
author = "Conquerix"
version = "v0.8.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a99d5c2a8da259faccaf4d8e8971519c8939a49b0ad084974416c0903cef1be"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
