name = "The InBetween"
author = "Conquerix"
version = "v0.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a1ce577b1e806f981f796bd712509eaf906df28d8004ee2d654f177ac97666b"

[versions]
fabric = "0.14.21"
minecraft = "1.19.2"
