name = "The-InBetween"
author = "Conquerix"
version = "v0.8.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9f0cbe2b6bcddd7efb7296916996f3f1ca97e7e74417964e7fadce65c6cce4a1"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
