name = "The-InBetween"
author = "Conquerix"
version = "v0.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "21cd298053152d51f23f031b83fdf8334b001d2f1132a363fd64621e4cf84ecc"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
