name = "The-InBetween"
author = "Conquerix"
version = "v0.8.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bd1f0e42b3b374d0c7c4a68b3647c9abc0162edc98ac92b2504d9136556a0564"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
