name = "The-InBetween"
author = "Conquerix"
version = "v0.4.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "615cbbf67e96eac1d59bfe5f94d0d692851b2533a711bf13132137b0bb636dec"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
