name = "The-InBetween"
author = "Conquerix"
version = "v0.5.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5a93072681ea2e57dd2c9c356cda517dbc4a1d7b24f506f0a1764d974e33bfdc"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
