name = "The-InBetween"
author = "Conquerix"
version = "v0.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0381214702215502dbcd49412f639defae5ebc8b72a914908bd9843477aec45d"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
