name = "The-InBetween"
author = "Conquerix"
version = "v0.4.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b0fb2eb7f91b59d6fe7f65611ad6d76a60fec640bd9a820d320ea1d20c97871"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
