name = "The-InBetween"
author = "Conquerix"
version = "v0.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b22f4c04e719c4c5953801e9bd4ad92b3aae9b004d0ce1f5e482ee80a55e3ba6"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
