name = "The-InBetween"
author = "Conquerix"
version = "v0.5.5"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a3a2345e4c556f83d111b23da8e776c2c19da44cb3b6de270889121f0530785b"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
