name = "The-InBetween"
author = "Conquerix"
version = "v0.5.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37da01d5e8a1692670f485578726938b19e375104522e23cce59ebb852cce84e"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
