name = "The-InBetween"
author = "Conquerix"
version = "v0.9.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90d0796ee2ed292182cda5dd53366acdc1fe7e4e7a8a6fe9363a154b967936f0"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
