name = "The-InBetween"
author = "Conquerix"
version = "v0.8.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f6084c5ff3f3ac9afd7890e71c91ebbb862cf70d655d352c43c5b26884a7231"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
