name = "The-InBetween"
author = "Conquerix"
version = "v0.8.9"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b20f6483a452dd416d5ebd509d900608f212385d218992ce85d92470e39022a"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
