name = "The-InBetween"
author = "Conquerix"
version = "v0.9.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c7b09e1793e2f94152a5f803821fa3e8beb2438afc3b1b9f94b1992c12da6a1"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
