name = "The-InBetween"
author = "Conquerix"
version = "v0.5.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9ef8cc4f0c5b529a2072615b1984ae79cc241e9965ca06bfd69ccf5463365601"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
