name = "The-InBetween"
author = "Conquerix"
version = "v0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ac4f437d8393d84ca0dc1b561ce6253d0178172654faee8a265005b08ad87d26"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
