name = "The-InBetween"
author = "Conquerix"
version = "v0.8.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9368151d393f14ceaab962e39d18f6f8ef458b6797ee5ffafd02f001dbc10f1a"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
