name = "The-InBetween"
author = "Conquerix"
version = "v0.8.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5831a99f748fd173d75df82b19a21178a922f6dc5133e3dc037be80126df02e"

[versions]
fabric = "0.15.10"
minecraft = "1.20.1"
