name = "The-InBetween"
author = "Conquerix"
version = "v0.3.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "083bd62978cde8e35433a4b0dc95e51dc4bd8d260eb7991bccaabf5a87ddb876"

[versions]
fabric = "0.14.24"
minecraft = "1.20.1"
