name = "The-InBetween"
author = "Conquerix"
version = "v0.4.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a159ee49532c1614fb18477aba5eff3fca7500793117cf3c7dedd192b85b7c93"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
