name: Modpack Release | Pipeline

on:
  push:
    branches:
      - main

env:
  pack-file: 'pack.toml'
  default-release-curseforge: 'true'


jobs:

  release-please:

    name: Handle Releases

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:      

      # --- Release please

      - name: Perform Release with Release Please
        id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: simple
          package-name: The-InBetween
          prerelease: true
          changelog-types: > 
            [{"type":"feat","section":"★ Features","hidden":false},
            {"type":"fix","section":"♻ Bug Fixes","hidden":false},
            {"type":"mod","section":"☀ Modpack Changes","hidden":false},
            {"type":"update","section":"⚘ Modpack Updates","hidden":false},
            {"type":"chore","section":"⛭ Miscellaneous","hidden":true}]

      - name: Check Out Git Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # #### Following executed IF new release is triggered.

      - name: Bump version
        uses: ./.github/actions/bump-pack
        with:
          release-tag: ${{ steps.release-please.outputs.tag_name }}
        if: ${{ steps.release-please.outputs.releases_created }}

      # --- Build an release

      - name: Build modpack
        uses: ./.github/actions/build
        with:
          release-tag: ${{ steps.release-please.outputs.tag_name }}
        if: ${{ steps.release-please.outputs.releases_created }}

      - name: Release modpack to vendors
        uses: ./.github/actions/release
        with:
          loader: "fabric"
          game-version: "1.19.2"
          upload-curse: true
          CURSEFORGE-ID: ${{ secrets.CURSEFORGE_ID }}
          CURSEFORGE-TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
        if: ${{ steps.release-please.outputs.releases_created }}
